### PR TITLE
Sprint7 development

### PR DESCRIPTION
**Pull request by prcox**
refactored entire frontend codebase to handle a new system of backend fetch calls

### CODE REVIEW

**Review by dnguyen3031 — APPROVED** [review]
All good! Everything follows the linter and the code is much more organized now!

**Review by maxchristy — APPROVED** [review]
Lots of changes here! From looking at the current build, it runs just fine so it looks good!

**Review by xhwallace — APPROVED** [review]
Looks Good to me.

**Review by jlu51 — APPROVED** [review]
Refactored code looks good!

**Pull request merged**
